### ISSUE TITLE
drucker dialog

### ISSUE THREAD

**Issue by jo-ei** [Schaffenburg/photobooth#1]
Hi,
man sollte in der config Datei die Möglichkeit schaffen den Druckerdialog komplett auszublenden wenn mal kein Drucker angeschlossen ist.

Auch wäre ein timeout bei keiner Aktion schön (so lange dann das gemacht Bild anzeigen)

**Comment by fraxinas** [comment]
Please file issues in english

The request was:
- implement a way to disable printing / printing dialog
- implement timeout after which it goes back into live preview 

both sound like good ideas!
i suggest using the existing copies_max key, disable printing if it's set to 0
there is timeout to go back to live preview but it only starts running if upload is enabled,
i'll implement another ini key for going from snapshot preview to live preview
