### ISSUE TITLE
correct application help

### ISSUE THREAD

**Issue by jo-ei** [Schaffenburg/photobooth#12]
Hi,
pleases correct the application help

```
Application Options:
  --display=DISPLAY          X display to use
```
to
```
Application Options:
  DISPLAY=:X  ./photobooth          X display to use
```

**Comment by fraxinas** [comment]
This is inherited from gtk+ and nothing that I can easily modify.
However it'll work the same way as using the DISPLAY environmental variable when using `--display=:X`. just don't forget the colon
