### ISSUE TITLE
Consider changing license

### ISSUE THREAD

**Issue by SZenglein** [Schaffenburg/photobooth#15]
Hello,

your license is rather limiting. May I ask if that is intentional and what the motivation behind that is? What do you think about re-licensing the project?

I think a copyleft license would still prevent people from abusing your work by forcing them to publish any changes.

**Comment by fraxinas** [comment]
Main reason for the CC license at the time being was that the software was unfit for commercial purpose and I think should generally stay out of any commercial context alltogether. All copyleft licenses which I am aware of don't limit commerical use.
Of course photobooth is still open for forking and modifications when publishing everything!
I know that CC is actually suboptimal for software projects, so please educate me @SZenglein

**Comment by SZenglein** [comment]
Additional information: Creative Commons also advices against using their licenses for software. I think GPLv3 could be an appropriate license, but that is obviously up to you.
[Source](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software)

**Comment by SZenglein** [comment]
Limiting commercial use is really off-putting. Somewhere you said you are taking "donations" for photos. You could argue this is earning money and if others do it you could sue them.  
I'm also not sure if just setting it up in a commercial context without actively earning money with it would be commercial use.

@fraxinas Do you want the software to stay out of commercial context because of its quality or because of the work you put in? If the former I wouldn't worry about it.

**Comment by fraxinas** [comment]
okay then I guess it's up to me to decide what I understand when I say commercial:

A non-profit organization like a hacker space using it and taking donations for the consumables: non-commercial

A for-profit company doing photos free of charge for the user, e.g. as a promotion: commercial

**Comment by SZenglein** [comment]
Ok, thanks for the clarification. Too bad, but also understandable, that you want to keep companies from using it.

**Comment by fraxinas** [comment]
Currently, it's still out of the question anyways :) The whole thing is by far not usable enough for anything serious. For example, it totally lacks packaging and we haven't really tested it with any other printer models.
I knew I'll have to deal with the license question at some point though.

**Comment by SZenglein** [comment]
I disagree. It's a DIY project after all and with a free software license you're not taking any responsibility. So the state doesn't really matter. People have to test their setup with camera and printer anyways.

I want something for the second use-case you described and I would have been happy to contribute testing and improvements.

**Comment by fraxinas** [comment]
You're very welcome to try. contact me under the provided email address
