### ISSUE TITLE
default pfad für Bilder

### ISSUE THREAD

**Issue by jo-ei** [Schaffenburg/photobooth#2]
Hi,
die gemachten Bilder sollten innerhalb der Anwendung als default liegen

default-template.ini
```
OLD: save_path_template = /home/fraxinas/Desktop/photobooth_%04d.jpg
NEW: save_path_template = ./images/photobooth_%04d.jpg
```

**Comment by fraxinas** [comment]
default save path should be relative to the current dir instead of in my home directory ^^ agreed
