### ISSUE TITLE
Bilder auf Kamera

### ISSUE THREAD

**Issue by jo-ei** [Schaffenburg/photobooth#3]
Hi,
es wäre schön wenn man in der config einstellen könnte, dass die Bilder auf der Kamera nicht gelöscht werden (als Backup des Rohbildes)

Sollte diese Zeile hier sein die dafür nicht mehr ausgeführt werden darf:
`gpret = gp_camera_file_delete (cam_info->camera, camera_file_path.folder, camera_file_path.name, cam_info->context);`

**Comment by fraxinas** [comment]
request is: optionally allow photos to remain on the camera instead of automatically deleting it, so that they can be kept as a backup.

accepted!

**Comment by fraxinas** [comment]
turned out to be a little trickier than supposed ><"

**Comment by fraxinas** [comment]
referenced in #11
